ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/barnatanyuval/red-hat-workshop'
  tag: 'v2'

service:
  servicePort: 8080

probes:
  readiness:
    path: '/templates/deployment'
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path: '/templates/deployment'
    initialDelaySeconds: 2
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

volume:
  mount:
    path: '/tmp/html'
